name: Lint Commit Messages

on: [pull_request]

permissions:
  contents: read

jobs:
  commitlint:
    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: read  # for wagoid/commitlint-github-action to get commits in PR
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@b948419dd99f3fd78a6548d48f94e3df7f6bf3ed # v6.2.1
        with:
          configFile: "./.github/commitlint.config.mjs"
